module.exports = {
  cfgfile:{
    crm:'configs/crm-mobile.js',
    build:{
      src:'configs/build-cfg.js',
      out:'tmp/Gruntfile.js'
    }
  },
  //配置文件夹
  configs:'configs',
  //临时文件夹
  temp:'tmp',
  //构建配置临时文件夹
  procfg:'tmp/procfg',
  //项目对应的文件夹
  procfgs:{
    'crm-mobile':'crm'
  }
}
